name: PR into main
on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Type Check
        run:  yarn type:check
      - name: Test
        run:  yarn test
